name: Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Hello World

     
      
